# Generated by Django 4.1.7 on 2023-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_avtofull_pay_day_childrenfull_pay_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtofullupload',
            name='sort_order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_en',
            field=models.CharField(blank=True, choices=[('Apartments', 'Apartments'), ('House', 'House'), ('Land', 'Land'), ('Commercial', 'Commercial'), ('Other', 'Other')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_ru',
            field=models.CharField(blank=True, choices=[('Апартаменты', 'Апартаменты'), ('Дом', 'Дом'), ('Земля', 'Земля'), ('Коммерческая недвижимость', 'Коммерческая недвижимость'), ('Другое', 'Другое')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='sub_category_tr',
            field=models.CharField(blank=True, choices=[('Daireler', 'Daireler'), ('Ev', 'Ev'), ('Kara', 'Kara'), ('Ticari gayrimenkul', 'Ticari gayrimenkul'), ('Diğer', 'Diğer')], default=None, max_length=255, null=True),
        ),
    ]
