# Generated by Django 4.1.7 on 2023-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_childrenfullupload_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='link',
            field=models.CharField(default='kibtop.com', max_length=255),
            preserve_default=False,
        ),
    ]
