# Generated by Django 4.1.7 on 2023-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_remove_stock_desc_en_remove_stock_desc_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='img_en',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='img_ru',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='img_tr',
        ),
        migrations.AddField(
            model_name='stock',
            name='image_en',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image_mobile_en',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение RU'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image_mobile_ru',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение RU'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image_mobile_tr',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение RU'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image_ru',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image_tr',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Изображение'),
        ),
    ]
