# Generated by Django 4.1.7 on 2023-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_remove_stock_img_en_remove_stock_img_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='background',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='img',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='isDark',
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_mobile',
            field=models.FileField(upload_to='stock/', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_mobile_en',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_mobile_ru',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_mobile_tr',
            field=models.FileField(null=True, upload_to='stock/', verbose_name='Мобильное изображение'),
        ),
    ]
