# Generated by Django 4.1.7 on 2023-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category_key',
            field=models.CharField(choices=[('realty', 'realty'), ('work', 'work'), ('services', 'services'), ('free', 'free'), ('avto', 'avto'), ('house_garden', 'house_garden'), ('electronics', 'electronics'), ('children', 'children'), ('fashion', 'fashion'), ('kibtop', 'kibtop')], max_length=100),
        ),
    ]
